---
language: python
python: "3"

services:
  - docker

sudo: false

# Install pip
addons:
  apt:
    packages:
      - python-pip

install:
  - pip install -r requirements.txt

script:
  # Lint check
  - ansible-lint -c test/lint/.ansible-lint .

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/