---
- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: true
  when: pantheon_managed_service

- name: Restart Pantheon
  service:
    name: pantheon
    state: restarted
  become: true
  when: pantheon_managed_service
